export const _CREATEACCOUNT = 'CREATEACCOUNT';
export const _LOGGEDIN = 'LOGGEDIN';

export const _CREATEPROJECT = 'CREATEPROJECT';
export const _DELETEPROJECT = 'DELETEPROJECT';

export const _CREATEFEED = 'CREATEFEED';
